USE [master]
GO
/****** Object:  Database [szin]    Script Date: 4/24/2021 6:51:36 PM ******/
CREATE DATABASE [szin]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'szin', FILENAME = N'D:\SQL-DATA\MSSQL15.DEV2019\MSSQL\Data\szin.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'szin_log', FILENAME = N'D:\SQL-DATA\MSSQL15.DEV2019\MSSQL\Data\szin_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 COLLATE Hungarian_CI_AS
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [szin] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [szin].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [szin] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [szin] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [szin] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [szin] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [szin] SET ARITHABORT OFF 
GO
ALTER DATABASE [szin] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [szin] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [szin] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [szin] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [szin] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [szin] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [szin] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [szin] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [szin] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [szin] SET  DISABLE_BROKER 
GO
ALTER DATABASE [szin] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [szin] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [szin] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [szin] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [szin] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [szin] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [szin] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [szin] SET RECOVERY FULL 
GO
ALTER DATABASE [szin] SET  MULTI_USER 
GO
ALTER DATABASE [szin] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [szin] SET DB_CHAINING OFF 
GO
ALTER DATABASE [szin] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [szin] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [szin] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [szin] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'szin', N'ON'
GO
ALTER DATABASE [szin] SET QUERY_STORE = OFF
GO
USE [szin]
GO
/****** Object:  Table [dbo].[Color]    Script Date: 4/24/2021 6:51:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Color](
	[ColorId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) COLLATE Hungarian_CI_AS NOT NULL,
	[Comments] [nvarchar](max) COLLATE Hungarian_CI_AS NULL,
 CONSTRAINT [PK_Color] PRIMARY KEY CLUSTERED 
(
	[ColorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_Color] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProductSchemaColorAssoc]    Script Date: 4/24/2021 6:51:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProductSchemaColorAssoc](
	[ProductSchemaColorAssocId] [int] IDENTITY(1,1) NOT NULL,
	[ProductSchemaId] [int] NOT NULL,
	[ColorId] [int] NOT NULL,
 CONSTRAINT [PK_ProductSchemaColorAssoc] PRIMARY KEY CLUSTERED 
(
	[ProductSchemaColorAssocId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_ProductSchemaColorAssoc] UNIQUE NONCLUSTERED 
(
	[ProductSchemaId] ASC,
	[ColorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProductSchema]    Script Date: 4/24/2021 6:51:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProductSchema](
	[ProductSchemaId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](200) COLLATE Hungarian_CI_AS NOT NULL,
	[Revision] [nvarchar](50) COLLATE Hungarian_CI_AS NULL,
	[SAPProductCode] [int] NULL,
	[ApprovalDate] [datetime2](7) NULL,
	[DrawingNr] [nvarchar](50) COLLATE Hungarian_CI_AS NULL,
	[SerialNr] [nvarchar](50) COLLATE Hungarian_CI_AS NULL,
	[Comments] [nvarchar](max) COLLATE Hungarian_CI_AS NULL,
 CONSTRAINT [PK_ProductSchema] PRIMARY KEY CLUSTERED 
(
	[ProductSchemaId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_ProductSchema] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[ProductSchemaColorAssoc]  WITH CHECK ADD  CONSTRAINT [FK_ProductSchemaColorAssoc_Color] FOREIGN KEY([ColorId])
REFERENCES [dbo].[Color] ([ColorId])
GO
ALTER TABLE [dbo].[ProductSchemaColorAssoc] CHECK CONSTRAINT [FK_ProductSchemaColorAssoc_Color]
GO

ALTER TABLE [dbo].[ProductSchemaColorAssoc]  WITH CHECK ADD  CONSTRAINT [FK_ProductSchemaColorAssoc_ProductSchema] FOREIGN KEY([ProductSchemaId])
REFERENCES [dbo].[ProductSchema] ([ProductSchemaId])
GO
ALTER TABLE [dbo].[ProductSchemaColorAssoc] CHECK CONSTRAINT [FK_ProductSchemaColorAssoc_ProductSchema]
GO
USE [master]
GO
ALTER DATABASE [szin] SET  READ_WRITE 
GO
